### ISSUE TITLE
Warnings on the version of pip and pipenv

### ISSUE THREAD

**Issue by marc-dms** [IBM/python-django-app#60]
Hi,

When I deploy automatically on a Cloud Foundry Application in IBM cloud, I get this warning. What should I do get ride of it? 

```
WARNING: You are using pip version 19.2.3, however version 20.0.2 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
```

I tried playing with Dockerfile and Dockerfile-tools files in the distribution but with no effect. When do these files come into play? 

Best, 

-- M

**Comment by gee4vee** [comment]
Thanks for the issue @marc-dms. Just to confirm, what are the commands you are executing?

**Comment by marc-dms** [comment]
I am using IBM "delivery pipeline". This takes place during the "Rolling deploy" step. I get an earlier warning BTW:

`
Deprecation warning: Use of 'buildpack' attribute in manifest is deprecated in favor of 'buildpacks'. Please see https://docs.cloudfoundry.org/devguide/deploy-apps/manifest-attributes.html#deprecated for alternatives and other app manifest deprecations. This feature will be removed in the future.
`

Does that answer your question?

**Comment by gee4vee** [comment]
So for Cloud Foundry deployments, we use the Python buildpack which manages its own dependencies in the operating system. I suspect the warning is coming from that buildpack having an older version of `pip`. I suggest opening an issue with that buildpack at https://github.com/cloudfoundry/python-buildpack/issues. Since the starter kit is working properly the warning can be safely ignored. I'll close this but please reopen if you find this issue is preventing the created app from working properly.

As for the deprecation warning about the `buildpack` attribute, we'll track that internally and fix it.
